name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: install-themes
        run: npm run refresh-themes

      - name: Build/release Electron app
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.github_token }}
